export const hotels1 = [
  {
    name: "Vdara Hotel & Spa at Aria Las Vegas",
    city: "Las Vegas",
    price: "$308",
    stars: 5,
    point: 4.5,
    reviews: "20,924",
    image: "/images/rmca.jpg",
  },
  {
    name: "Trump International Hotel Las Vegas",
    city: "Las Vegas",
    price: "$145",
    stars: 5,
    point: 4.5,
    reviews: "15,557",
    image: "/images/rmca1.jpg",
  },
  {
    name: "The Cosmopolitan of Las Vegas",
    city: "Las Vegas",
    price: "$449",
    stars: 5,
    point: 4.0,
    reviews: "1,971",
    image: "/images/rmca2.jpg",
  },
  {
    name: "Hotel Riu Plaza New York Time Square",
    city: "New York",
    price: "$204",
    stars: 4,
    point: 4.5,
    reviews: "5,401",
    image: "/images/mca.jpg",
  },
  {
    name: "Even Hotel New York Times Square South, an IHG Hotel",
    city: "New York",
    price: "$162",
    stars: 4,
    point: 4.5,
    reviews: "1,640",
    image: "/images/mca1.jpg",
  },
  {
    name: "Wyndham Garden Chinatown",
    city: "New York",
    price: "$115",
    stars: 4,
    point: 4.5,
    reviews: "2,305",
    image: "/images/mca2.jpg",
  },
  {
    name: "SpringHill Suits by Marriot Orlando at MIllenia",
    city: "Orlando",
    price: "$115",
    stars: 4,
    point: 4.5,
    reviews: "2,305",
    image: "/images/orlando2.jpg",
  },
  {
    name: "Universal´s Loews Royal Pacific Resort",
    city: "Orlando",
    price: "$336",
    stars: 4,
    point: 4.5,
    reviews: "15,895",
    image: "/images/orlando1.jpg",
  },
  {
    name: "Hilton Grand Vacations Club Tuscany Village Orlando",
    city: "Orlando",
    price: "$159",
    stars: 4,
    point: 4.5,
    reviews: "6,321",
    image: "/images/orlando.jpg",
  },
  {
    name: "InterContinental Miami, an IHG Hotel",
    city: "Miami",
    price: "$259",
    stars: 4,
    point: 4.5,
    reviews: "7,600",
    image: "/images/miami.jpg",
  },
  {
    name: "Kimpton Epic Hotel, an IHG Hotel",
    city: "Miami",
    price: "$309",
    stars: 4,
    point: 4.5,
    reviews: "4,204",
    image: "/images/miami1.jpg",
  },
  {
    name: "Novotel Miami Brickell",
    city: "Miami",
    price: "$276",
    stars: 4,
    point: 4.5,
    reviews: "2,821",
    image: "/images/miami2.jpg",
  },
  {
    name: "Loews Hollywood Hotel",
    city: "Los Angeles",
    price: "$227",
    stars: 4,
    point: 4.5,
    reviews: "5,112",
    image: "/images/lag.jpg",
  },
  {
    name: "Luxe Sunset Boulevard Hotel",
    city: "Los Angeles",
    price: "$171",
    stars: 4,
    point: 4.5,
    reviews: "1,950",
    image: "/images/lag1.jpg",
  },
  {
    name: "Hotel Indigo - Los Angeles Downtown, an IHG Hotel",
    city: "Los Angeles",
    price: "$189",
    stars: 4,
    point: 4.5,
    reviews: "901",
    image: "/images/lag2.jpg",
  },
];

export const hotels2 = [
  {
    name: "Hilton Grand Vacations Club Elara Center Strip Las Vegas",
    city: "Las Vegas",
    price: "$347",
    stars: 4,
    point: 4.5,
    reviews: "8,387",
    image: "/images/la1.jpg",
  },
  {
    name: "Hilton Garden Inn Las Vegas Strip South",
    city: "Las Vegas",
    price: "$317",
    stars: 3,
    point: 4.5,
    reviews: "1,371",
    image: "/images/la2.jpg",
  },
  {
    name: "Home2 Suits by Hilton Las Vegas Strip South",
    city: "Las Vegas",
    price: "$342",
    stars: 3,
    point: 4.5,
    reviews: "223",
    image: "/images/la3.jpg",
  },
  {
    name: "Wyndham Garden Chinatown",
    city: "New York",
    price: "$108",
    stars: 4,
    point: 4.5,
    reviews: "2,305",
    image: "/images/ny1.jpg",
  },
  {
    name: "The Benjamin Royal Sonesta New York",
    city: "New York",
    price: "$188",
    stars: 5,
    point: 4.5,
    reviews: "3,446",
    image: "/images/ny2.jpg",
  },
  {
    name: "Hilton Garden Inn Times Square",
    city: "New York",
    price: "$97",
    stars: 3,
    point: 4.5,
    reviews: "9,015",
    image: "/images/ny3.jpg",
  },
  {
    name: "DoubleTree by Hilton Orlando East-UCF Area",
    city: "Orlando",
    price: "$125",
    stars: 4,
    point: 4.5,
    reviews: "1,393",
    image: "/images/o1.jpg",
  },
  {
    name: "Drury Inn & Suits Near Universal Orlando Resort",
    city: "Orlando",
    price: "$112",
    stars: 3,
    point: 4.5,
    reviews: "2,820",
    image: "/images/o2.jpg",
  },
  {
    name: "Hampton Inn Closest to Universal Orlando",
    city: "Orlando",
    price: "$100",
    stars: 2,
    point: 4.5,
    reviews: "1,474",
    image: "/images/o3.jpg",
  },
  {
    name: "Mr.C Miami - Coconut Grove",
    city: "Miami",
    price: "$392",
    stars: 5,
    point: 4.5,
    reviews: "317",
    image: "/images/m1.jpg",
  },
  {
    name: "Mandarin Oriental, Miami",
    city: "Miami",
    price: "$626",
    stars: 5,
    point: 4.5,
    reviews: "3,503",
    image: "/images/m2.jpg",
  },
  {
    name: "Four Seasons Hotel Miami",
    city: "Miami",
    price: "$1,280",
    stars: 5,
    point: 4.5,
    reviews: "2,330",
    image: "/images/m3.jpg",
  },
  {
    name: "The Hollywood Rosevelt",
    city: "Los Angeles",
    price: "$214",
    stars: 4,
    point: 4.5,
    reviews: "3,385",
    image: "/images/la.jpg",
  },
  {
    name: "Omni Los Angeles Hotel California Plaza",
    city: "Los Angeles",
    price: "$229",
    stars: 4,
    point: 4.5,
    reviews: "4,409",
    image: "/images/la1.jpg",
  },
  {
    name: "Dream Hollywood",
    city: "Los Angeles",
    price: "$251",
    stars: 4,
    point: 4.5,
    reviews: "955",
    image: "/images/la2.jpg",
  },
];

export const cards = [
  {
    id: 1,
    title: "Miami",
    image: "/images/miami.webp",
  },
  {
    id: 2,
    title: "New York",
    image: "/images/newyork.webp",
  },
  {
    id: 3,
    title: "Las Vegas",
    image: "/images/lasvegas.webp",
  },
  {
    id: 4,
    title: "Los Angeles",
    image: "/images/losangeles.webp",
  },
  {
    id: 5,
    title: "Denver",
    image: "/images/denver.webp",
  },
  {
    id: 6,
    title: "Chicago",
    image: "/images/chicago.webp",
  },
  {
    id: 7,
    title: "Orlando",
    image: "/images/orlando.webp",
  },
  {
    id: 8,
    title: "San Francisco",
    image: "/images/sanfrancisco.webp",
  },
  {
    id: 9,
    title: "Washington",
    image: "/images/washington.webp",
  },
];
